### ISSUE TITLE
FR15. Settings Menu

### ISSUE THREAD

**Issue by JacobJGood** [WSU-4110/Notely#12]
|FR15. Settings Menu|
|---|
|**Goal**: A settings page allowing users to change aspects of the app.|
|**Stakeholders:** Users.|
| **Description:** The user will have the option to view a settings page. The settings page will allow the user to adjust various elements of the app. This would include the privacy feature.|
| **Origin:** Discussed during initial group design meeting.|
| **Version:** 1.0.0  |  
|**Date:** 01/29/2021  |
|  **Priority:** 1 |

**Comment by christian-anthony** [comment]
The settings menu is within the app but does not currently have functionality.
Functionality has not been implemented due to time constraints
