### ISSUE TITLE
FR4. Advanced Search

### ISSUE THREAD

**Issue by JulianGombosWSU** [WSU-4110/Notely#14]
|FR4.  Advanced Search|
|---|
|**Goal**: Advanced search will allow users to search with really specific rulesets that can help yield more accurate results.|
|**Stakeholders:** Users|
| **Description:** The advanced search would be associated with the main menu options. When using advanced search, users will be able to filter results using tags. Any tags that were added to a post would be utilized here. This is a feature that is unavailable to the normal search feature. The results of advanced search will be displayed the same way that they would from the normal search feature. Advanced search will help allow users to quickly find posts relevant to their needs. |
| **Origin:** Part of the original mockup design.|
| **Version:** 1.0.0  |  
|**Date:** 01/29/2021 | 
|  **Priority:** 2 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
