### ISSUE TITLE
NR4: Real-Time Updates from Database

### ISSUE THREAD

**Issue by go5486** [WSU-4110/Notely#17]
|NR4: Real-Time Updates from Database|
|---|
|**Goal**: Posts will appear in the app in real time. |
|**Stakeholders:** All|
| **Description:**  Changes made to the database from within the app will be shared in real-time. This includes uploading posts and adding tags. Other users will be able to see changes shortly after the modification is made.  |
| **Origin:** Discussed during initial group design meeting. |
| **Version:** 1.0.0 |  
|**Date:** 1/29/2021 |  
|  **Priority:** 5 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
