### ISSUE TITLE
NR5: Starting Tutorial

### ISSUE THREAD

**Issue by go5486** [WSU-4110/Notely#19]
|NR5: Starting Tutorial|
|---|
|**Goal**: Instruct the user on navigation and use of the application.|
|**Stakeholders:** All|
| **Description:** Once a user creates a new account, a series of tutorial prompts should appear on the screen the first time they use the app. Users will be able to opt out of the tutorial. Once the user has completed the tutorial, the prompts will never appear again unless there are significant changes to the app. |
| **Origin:** Discussed during initial group design meeting. |
| **Version:** 1.0.0 |  
|**Date:** 1/29/2021 |  
|  **Priority:** 5 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
