### ISSUE TITLE
FR12. Posts can be Flagged for Misconduct

### ISSUE THREAD

**Issue by JacobJGood** [WSU-4110/Notely#21]
|FR12. Posts can be Flagged for Misconduct|
|---|
|**Goal**: Make a safe and appropriate environment for all ages over 13.|
|**Stakeholders:** All.|
| **Description:** A UI element will exist on all posts that will allow users to flag them if they are inappropriate. If a user flags a post, a warning prompt will appear to the user with a notice for confirmation. Users will have to ‘OK’ the warning for the flag to be finalized. Posts that are flagged multiple times will not appear in the app until review.|
| **Origin:** Discussed during initial group design meeting.|
| **Version:** 1.0.0  |  
|**Date:** 01/29/2021  |
|  **Priority:** 1 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
