### ISSUE TITLE
FR3. Search Bar

### ISSUE THREAD

**Issue by JulianGombosWSU** [WSU-4110/Notely#5]
|FR3.  Search Bar|
|---|
|**Goal**:  The search bar will allow users to search the database of posts and find the specific one(s) they are looking for.|
|**Stakeholders:** Users|
| **Description:** A search bar will be available to the user through a UI element. Users can search either by using the class name or keywords in the post title. The search results would then be vertically filled on the screen assuming that the search yielded more than one result. The user can then scroll through the posts on the screen.|
| **Origin:** Part of the original mockup design.|
| **Version:** 1.0.0  |  
|**Date:** 01/29/2021  
|  **Priority:** 2 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
