### ISSUE TITLE
NR1: Authentication Verification

### ISSUE THREAD

**Issue by go5486** [WSU-4110/Notely#6]
|NR1: Authentication Verification |
|---|
|**Goal**: The goal is to make sure the account creators are real people. |
|**Stakeholders:** All|
| **Description:** Description: Upon creating an account, the user will be prompted to complete a captcha. This will verify that the user is not automated. There are many forms of captcha authentication, the one we will use reCaptcha. Account creators must first select the checkbox that reads “I am not a robot”. They will then be asked to select all the images from a 9 image selection that contain the randomly generated object. If a user fails the captcha, they will be redirected to the login page. |
| **Origin:** Discussed during initial group design meeting. |
| **Version:** 1.0.0 |  
|**Date:** 1/29/2021 |  
|  **Priority:** 3 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
