### ISSUE TITLE
FR14. Anonymous Username Mode

### ISSUE THREAD

**Issue by JacobJGood** [WSU-4110/Notely#8]
|FR14. Anonymous Username Mode|
|---|
|**Goal**: Allowing users the option to stay anonymous from other users when posting.|
|**Stakeholders:** All.|
| **Description:** Some users may wish to view or upload posts discreetly. In the user’s settings, there will be a UI element that will change the user’s profile to private, making it unviewable by other users. The user’s name will be hidden on their posts. Location data for these posts will be private.|
| **Origin:** Discussed during initial group design meeting.|
| **Version:** 1.0.0  |  
|**Date:** 01/29/2021  |
|  **Priority:** 1 |

**Comment by christian-anthony** [comment]
This feature has not been implemented due to time constraints
